//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ask_The_Tree.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("What are the specialties of the Pediatric Department at King Faisal Specialist Ho" +
            "spital And Research Center?")]
        public string btn1E {
            get {
                return ((string)(this["btn1E"]));
            }
            set {
                this["btn1E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("What is Cystic Fibrosis?")]
        public string btn2E {
            get {
                return ((string)(this["btn2E"]));
            }
            set {
                this["btn2E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("What is the importance of vaccination for children?")]
        public string btn3E {
            get {
                return ((string)(this["btn3E"]));
            }
            set {
                this["btn3E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("What is primary immunodeficiency?")]
        public string btn4E {
            get {
                return ((string)(this["btn4E"]));
            }
            set {
                this["btn4E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("How to choose what is healthy for your child?")]
        public string btn5E {
            get {
                return ((string)(this["btn5E"]));
            }
            set {
                this["btn5E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Why is breastfeeding recommended for your child?")]
        public string btn6E {
            get {
                return ((string)(this["btn6E"]));
            }
            set {
                this["btn6E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("How to protect your child from traffic accident injuries?")]
        public string btn7E {
            get {
                return ((string)(this["btn7E"]));
            }
            set {
                this["btn7E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Are there types of diabetes?")]
        public string btn8E {
            get {
                return ((string)(this["btn8E"]));
            }
            set {
                this["btn8E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Is violence limited to physical violence?")]
        public string btn9E {
            get {
                return ((string)(this["btn9E"]));
            }
            set {
                this["btn9E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ماهي التخصصات التي يشملها قسم طب الأطفال في مستشفى الملك فيصل التخصصي ومركز الأبح" +
            "اث؟  ")]
        public string btn1A {
            get {
                return ((string)(this["btn1A"]));
            }
            set {
                this["btn1A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ماهو مرض التليف الكيسي الرئوي البنكرياسي؟  ")]
        public string btn2A {
            get {
                return ((string)(this["btn2A"]));
            }
            set {
                this["btn2A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ما أهمية اللقاحات الأولية للأطفال؟  ")]
        public string btn3A {
            get {
                return ((string)(this["btn3A"]));
            }
            set {
                this["btn3A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ماهو مرض نقص المناعة الأولية؟  ")]
        public string btn4A {
            get {
                return ((string)(this["btn4A"]));
            }
            set {
                this["btn4A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("كيف تختار الطعام الصحي لطفلك؟  ")]
        public string btn5A {
            get {
                return ((string)(this["btn5A"]));
            }
            set {
                this["btn5A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ماذا ينصح بالرضاعة الطبيعية للطفل؟  ")]
        public string btn6A {
            get {
                return ((string)(this["btn6A"]));
            }
            set {
                this["btn6A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("كيف تقي طفلك من خطر الإصابة من الحوادث المرورية؟  ")]
        public string btn7A {
            get {
                return ((string)(this["btn7A"]));
            }
            set {
                this["btn7A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("هل هناك أنواع لمرض السكري؟  ")]
        public string btn8A {
            get {
                return ((string)(this["btn8A"]));
            }
            set {
                this["btn8A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("هل يقتصر العنف على العنف الجسدي؟  ")]
        public string btn9A {
            get {
                return ((string)(this["btn9A"]));
            }
            set {
                this["btn9A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording1.m4a")]
        public string btn1AudioA {
            get {
                return ((string)(this["btn1AudioA"]));
            }
            set {
                this["btn1AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording2.m4a")]
        public string btn2AudioA {
            get {
                return ((string)(this["btn2AudioA"]));
            }
            set {
                this["btn2AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording3.m4a")]
        public string btn3AudioA {
            get {
                return ((string)(this["btn3AudioA"]));
            }
            set {
                this["btn3AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording4.m4a")]
        public string btn4AudioA {
            get {
                return ((string)(this["btn4AudioA"]));
            }
            set {
                this["btn4AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording5.m4a")]
        public string btn5AudioA {
            get {
                return ((string)(this["btn5AudioA"]));
            }
            set {
                this["btn5AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording6.m4a")]
        public string btn6AudioA {
            get {
                return ((string)(this["btn6AudioA"]));
            }
            set {
                this["btn6AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording7.m4a")]
        public string btn7AudioA {
            get {
                return ((string)(this["btn7AudioA"]));
            }
            set {
                this["btn7AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording8.m4a")]
        public string btn8AudioA {
            get {
                return ((string)(this["btn8AudioA"]));
            }
            set {
                this["btn8AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording9.m4a")]
        public string btn9AudioA {
            get {
                return ((string)(this["btn9AudioA"]));
            }
            set {
                this["btn9AudioA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording1.m4a")]
        public string btn1AudioE {
            get {
                return ((string)(this["btn1AudioE"]));
            }
            set {
                this["btn1AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording2.m4a")]
        public string btn2AudioE {
            get {
                return ((string)(this["btn2AudioE"]));
            }
            set {
                this["btn2AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording3.m4a")]
        public string btn3AudioE {
            get {
                return ((string)(this["btn3AudioE"]));
            }
            set {
                this["btn3AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording4.m4a")]
        public string btn4AudioE {
            get {
                return ((string)(this["btn4AudioE"]));
            }
            set {
                this["btn4AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording5.m4a")]
        public string btn5AudioE {
            get {
                return ((string)(this["btn5AudioE"]));
            }
            set {
                this["btn5AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording6.m4a")]
        public string btn6AudioE {
            get {
                return ((string)(this["btn6AudioE"]));
            }
            set {
                this["btn6AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording7.m4a")]
        public string btn7AudioE {
            get {
                return ((string)(this["btn7AudioE"]));
            }
            set {
                this["btn7AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording8.m4a")]
        public string btn8AudioE {
            get {
                return ((string)(this["btn8AudioE"]));
            }
            set {
                this["btn8AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording9.m4a")]
        public string btn9AudioE {
            get {
                return ((string)(this["btn9AudioE"]));
            }
            set {
                this["btn9AudioE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string destPage {
            get {
                return ((string)(this["destPage"]));
            }
            set {
                this["destPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio Test/Recording10.m4a")]
        public string btnExtraAudio {
            get {
                return ((string)(this["btnExtraAudio"]));
            }
            set {
                this["btnExtraAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("افتتاح")]
        public string btnExtra {
            get {
                return ((string)(this["btnExtra"]));
            }
            set {
                this["btnExtra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn1Esize {
            get {
                return ((string)(this["btn1Esize"]));
            }
            set {
                this["btn1Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn2Esize {
            get {
                return ((string)(this["btn2Esize"]));
            }
            set {
                this["btn2Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn3Esize {
            get {
                return ((string)(this["btn3Esize"]));
            }
            set {
                this["btn3Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn4Esize {
            get {
                return ((string)(this["btn4Esize"]));
            }
            set {
                this["btn4Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn5Esize {
            get {
                return ((string)(this["btn5Esize"]));
            }
            set {
                this["btn5Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn6Esize {
            get {
                return ((string)(this["btn6Esize"]));
            }
            set {
                this["btn6Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn7Esize {
            get {
                return ((string)(this["btn7Esize"]));
            }
            set {
                this["btn7Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn8Esize {
            get {
                return ((string)(this["btn8Esize"]));
            }
            set {
                this["btn8Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn9Esize {
            get {
                return ((string)(this["btn9Esize"]));
            }
            set {
                this["btn9Esize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn1Asize {
            get {
                return ((string)(this["btn1Asize"]));
            }
            set {
                this["btn1Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn2Asize {
            get {
                return ((string)(this["btn2Asize"]));
            }
            set {
                this["btn2Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn3Asize {
            get {
                return ((string)(this["btn3Asize"]));
            }
            set {
                this["btn3Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn4Asize {
            get {
                return ((string)(this["btn4Asize"]));
            }
            set {
                this["btn4Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn5Asize {
            get {
                return ((string)(this["btn5Asize"]));
            }
            set {
                this["btn5Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn6Asize {
            get {
                return ((string)(this["btn6Asize"]));
            }
            set {
                this["btn6Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn7Asize {
            get {
                return ((string)(this["btn7Asize"]));
            }
            set {
                this["btn7Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn8Asize {
            get {
                return ((string)(this["btn8Asize"]));
            }
            set {
                this["btn8Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string btn9Asize {
            get {
                return ((string)(this["btn9Asize"]));
            }
            set {
                this["btn9Asize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.0")]
        public string btnExtraSize {
            get {
                return ((string)(this["btnExtraSize"]));
            }
            set {
                this["btnExtraSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28.0")]
        public string btnBackEsize {
            get {
                return ((string)(this["btnBackEsize"]));
            }
            set {
                this["btnBackEsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28.0")]
        public string btnBackAsize {
            get {
                return ((string)(this["btnBackAsize"]));
            }
            set {
                this["btnBackAsize"] = value;
            }
        }
    }
}
